import React from "react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { useSwish } from "../context/SwishContext";
export default function Colleges() {
  const { colleges, addCollege, toggleCollege, users } = useSwish();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({name:"",code:"",domain:"",location:""});
  const submit = e => { e.preventDefault(); const r=addCollege(form); if(r.ok){setForm({name:"",code:"",domain:"",location:""});setOpen(false);} };
  return <div className="admin-shell"><aside className="admin-sidebar"><div className="brand">✦ SWISH ADMIN</div><nav><Link to="/admin">Dashboard</Link><Link className="active" to="/admin/colleges">Colleges</Link><Link to="/admin/moderation">Moderation</Link></nav></aside><main className="admin-main"><div className="admin-header"><div><span className="eyebrow">COLLEGE MANAGEMENT</span><h1>Registered colleges</h1></div><button className="primary" onClick={()=>setOpen(true)}>＋ Add College</button></div><div className="table-panel"><table><thead><tr><th>College</th><th>Domain</th><th>Users</th><th>Status</th><th>Actions</th></tr></thead><tbody>{colleges.map(c=>{const count=users.filter(u=>u.college===c.name).length;return <tr key={c.id}><td><b>{c.name}</b><small>{c.code} • {c.location}</small></td><td>{c.domain}</td><td>{count.toLocaleString()}</td><td><span className={c.active?"status active":"status"}>{c.active?"ACTIVE":"DISABLED"}</span></td><td><button className="table-btn" onClick={()=>toggleCollege(c.id)}>{c.active?"Disable":"Activate"}</button></td></tr>})}</tbody></table></div>{open&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>Add College</h2><button onClick={()=>setOpen(false)}>×</button></div><form onSubmit={submit}><input required placeholder="College Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="College Code" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><input required placeholder="Official Email Domain e.g. @college.edu.in" value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}/><input required placeholder="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><button className="primary full">Save & Activate</button></form></div></div>}</main></div>;
}